a = int(10)
b = str("Hello World?")
print(a)
print(type(a))
print(b)
print(type(b))

c = input("Введите Ваше имя:")
d = input("Введите Ваш возраст:")
print(f"Ваше имя: {str(c)}, Ваш возраст: {int(d)}")
